### ISSUE TITLE
Window Resizing doesn't work in triangle example

### ISSUE THREAD

**Issue by FuujSama** [vulkano-rs/vulkano-examples#19]
So I got the example running fairly straight forward, yet it doesn't seem like resizing the window is triggering an out of date error in acquire_next_image(). 
So I just get a black image until I resize it back to the original size. 

Is there some other way of figuring out when the window has been resized?

**Comment by JohnDoneth** [comment]
I wonder if this is related to issue #18 since they are both caused by resizing. However the error there is `DeviceLost`. What Operating System, GPU, and drivers were you using?

**Comment by mpalomas** [comment]
As of today resizing the window is still not working on the very basic triangle example.

I am not sure I am facing the exact same bug as FuuSama: mine just crashes on resizing.

Windows 10 Pro 64 bit, running on GTX 1050

`
$env:RUST_BACKTRACE=1; cargo run --bin triangle
    Finished dev [unoptimized + debuginfo] target(s) in 0.29 secs
     Running `target\debug\triangle.exe`
Using device: GeForce GTX 1050 (type: DiscreteGpu)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfDate', libcore\result.rs:945:5
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:205
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:221
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:457
   6: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:344
   7: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:322
   8: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   9: core::result::unwrap_failed<vulkano::sync::future::FlushError>
             at C:\projects\rust\src\libcore\macros.rs:26
  10: core::result::Result<vulkano::sync::future::fence_signal::FenceSignalFuture<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>, vulkano::sync::future::FlushError>::unwrap<vulkano::sync::future::fence_signal::FenceSignalFuture<vulkano::swapchain::swapchain::PresentFuture<vulkano::command_buffer::traits::CommandBufferExecFuture<vulkano::sync::future::join::JoinFuture<alloc::boxed::Box<GpuFuture>, vulkano::swapchain::swapchain::SwapchainAcquireFuture<winit::Window>>, vulkano::command_buffer::auto::AutoCommandBuffer<vulkano::command_buffer::pool::standard::StandardCommandPoolAlloc>>, winit::Window>>,vulkano::sync::future::FlushError>
             at C:\projects\rust\src\libcore\result.rs:782
  11: triangle::main
             at .\triangle\main.rs:440
`

**Comment by sgodwincs** [comment]
I also run into the same problem (`OutOfDate` at [main.rs#L440](https://github.com/vulkano-rs/vulkano-examples/blob/master/triangle/main.rs#L440)) . Running Windows 10 Pro 64 bit, GTX 750 Ti

**Comment by JohnDoneth** [comment]
@mpalomas @sgodwincs These examples are not as up to date with regards to these errors as the [ones in the main vulkano repository](https://github.com/vulkano-rs/vulkano/tree/master/examples/src/bin). I would suggest looking at those examples, and maybe even submit a pull request to merge the fixes into this repository if you have the time.
