### ISSUE TITLE
examples don't run on linux

### ISSUE THREAD

**Issue by portaloffreedom** [vulkano-rs/vulkano-examples#20]
I'm running archlinux with kde plasma. Not sure what combination is killing the examples, but this is the error message:
```
Using device: GeForce GTX 1080 Ti (type: DiscreteGpu)
thread 'main' panicked at 'failed to create swapchain: UnsupportedDimensions', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I think the problem may be that the window is created on default with dimensions (0, 0). Therefore when creating the swapchain, it crashes.

Adding `.with_dimensions(800, 600)` to the window builder fixed it for me.

P.S.
`msaa-renderpass` works fine

**Comment by rukai** [comment]
I cant reproduce the issue.
Can you check if the issue still occurs on this branch https://github.com/rukai/vulkano-examples/tree/revamp
(It updates the examples to use the latest version of vulkano + winit)

**Comment by portaloffreedom** [comment]
True, in your branch the issue seems disappeared as well.
Also, the master branch of this project seems to be working ok.
