### ISSUE TITLE
Memory leak in deferred example

### ISSUE THREAD

**Issue by mikhailv** [vulkano-rs/vulkano-examples#5]
Hi, I have noticed that running 'deferred' example project is continuously allocating memory. Not sure if it's example code issue or vulkano library issue. Here screenshot from task manager (I know this is rough detection of memory leak):
![deferred-example](https://user-images.githubusercontent.com/527152/30068558-d1d98c22-9266-11e7-8451-1d4012d6f5a5.png)

For example similar screenshot for 'triangle' project:
![triangle-example](https://user-images.githubusercontent.com/527152/30068618-009dfe4e-9267-11e7-91ef-8ba944abd542.png)

Windows 10 Pro 64-bit (10.0, Build 15063)
NVidia GTX 1070 (driver 384.76)
rustc 1.20.0 (f3d6973f4 2017-08-27)

**Comment by tomaka** [comment]
Thanks for the report.
I can reproduce on my machine, however after inspecting the API calls made by vulkano and can't find the source of the leak.

**Comment by tomaka** [comment]
https://github.com/vulkano-rs/vulkano/pull/800 seems to considerably decrease the speed of the leak. Even though there shouldn't be any leak (even before the PR), I suspect that the nVidia driver simply supposes that you never destroy your pools and may not correctly clean them up.

**Comment by tomaka** [comment]
https://github.com/crossbeam-rs/crossbeam/issues/91 is also a possible cause, but updating crossbeam alone didn't fix the leak either.

**Comment by rukai** [comment]
I can confirm this is still occurring on windows with nvidia cards (GTX 960). It is not an issue with amd.

This issue will be moved to the main repo when https://github.com/vulkano-rs/vulkano/pull/1023 goes ahead.

**Comment by rukai** [comment]
Moved to https://github.com/vulkano-rs/vulkano/issues/1032
