### ISSUE TITLE
Repository plans?

### ISSUE THREAD

**Issue by LPGhatguy** [vulkano-rs/vulkano-examples#7]
Currently, the main Vulkano repository's example folder has more examples, many of which are necessary to get off the ground fully with Vulkano.

Which of those examples should be ported to vulkano-examples, and what changes should be made to them in the transition? Specifically, the debug, teapot, and image examples were super useful to me.

**Comment by tomaka** [comment]
> Which of those examples should be ported to vulkano-examples

All of them!

> what changes should be made to them in the transition?

The code should be cleaned up: better style, comments, and so on.

**Comment by David-OConnor** [comment]
What is the purpose of this repo, in relation to the examples in the main vulkano one?
